package filter

// GetDefaultFilters returns the default filter rules used to obfuscate sensitive terms
// These filters help bypass upstream detection by replacing brand names and identifiers
// Updated with 32 complete rules from xixero1445 template (aggressive mode)
func GetDefaultFilters() []FilterRule {
	return []FilterRule{
		// Brand names
		{
			ID:            "default_claude_code",
			Pattern:       "Claude Code",
			Replacement:   "Code Assistant",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_claude",
			Pattern:       "Claude",
			Replacement:   "CL4ude",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_anthropic",
			Pattern:       "Anthropic",
			Replacement:   "Anxthxropic",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_openai",
			Pattern:       "OpenAI",
			Replacement:   "0penAI",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_gpt",
			Pattern:       "GPT",
			Replacement:   "GxPT",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		// Jailbreak terms
		{
			ID:            "default_jailbreak",
			Pattern:       "Jailbreak",
			Replacement:   "J41lbreak",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_godmode",
			Pattern:       "godmode",
			Replacement:   "g0dmode",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_prompt_injection",
			Pattern:       "prompt injection",
			Replacement:   "prompt inj3ction",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_red_teaming",
			Pattern:       "red-teaming",
			Replacement:   "red-team1ng",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_bypass",
			Pattern:       "bypass",
			Replacement:   "byp4ss",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_exploit",
			Pattern:       "exploit",
			Replacement:   "expl0it",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_vulnerability",
			Pattern:       "vulnerability",
			Replacement:   "vuln3rability",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		// API identifiers
		{
			ID:            "default_cache_control",
			Pattern:       "cache_control",
			Replacement:   "",
			IsRegex:       false,
			CaseSensitive: true,
			IsActive:      true,
			Mode:          FilterModeRequestOnly,
		},
		{
			ID:            "default_cc_entrypoint",
			Pattern:       "cc_entrypoint",
			Replacement:   "app_entrypoint",
			IsRegex:       false,
			CaseSensitive: true,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_cc_version",
			Pattern:       "cc_version",
			Replacement:   "app_version",
			IsRegex:       false,
			CaseSensitive: true,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_claude_prefix",
			Pattern:       "claude-",
			Replacement:   "model-",
			IsRegex:       false,
			CaseSensitive: true,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_gpt_prefix",
			Pattern:       "gpt-",
			Replacement:   "llm-",
			IsRegex:       false,
			CaseSensitive: true,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_anthropic_api",
			Pattern:       "api.anxthxropic.com",
			Replacement:   "api.example.com",
			IsRegex:       false,
			CaseSensitive: true,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_openai_api",
			Pattern:       "api.openai.com",
			Replacement:   "api.example.com",
			IsRegex:       false,
			CaseSensitive: true,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		// Sensitive content markers
		{
			ID:            "default_sensitive_content",
			Pattern:       "sensitive_content",
			Replacement:   "flagged_content",
			IsRegex:       false,
			CaseSensitive: true,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_unsafe",
			Pattern:       "unsafe",
			Replacement:   "uns4fe",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_harmful",
			Pattern:       "harmful",
			Replacement:   "h4rmful",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_illegal",
			Pattern:       "illegal",
			Replacement:   "ill3gal",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_unethical",
			Pattern:       "unethical",
			Replacement:   "un3thical",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		// System prompts
		{
			ID:            "default_system_prompt",
			Pattern:       "system_prompt",
			Replacement:   "sys_prompt",
			IsRegex:       false,
			CaseSensitive: true,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_assistant_prompt",
			Pattern:       "assistant_prompt",
			Replacement:   "asst_prompt",
			IsRegex:       false,
			CaseSensitive: true,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_instruction",
			Pattern:       "instruction",
			Replacement:   "instr",
			IsRegex:       false,
			CaseSensitive: false,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		// Model identifiers
		{
			ID:            "default_claude_3_opus",
			Pattern:       "claude-3-opus",
			Replacement:   "model-3-opus",
			IsRegex:       false,
			CaseSensitive: true,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_claude_3_sonnet",
			Pattern:       "claude-3-sonnet",
			Replacement:   "model-3-sonnet",
			IsRegex:       false,
			CaseSensitive: true,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_claude_3_haiku",
			Pattern:       "claude-3-haiku",
			Replacement:   "model-3-haiku",
			IsRegex:       false,
			CaseSensitive: true,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_gpt_4",
			Pattern:       "gpt-4",
			Replacement:   "llm-4",
			IsRegex:       false,
			CaseSensitive: true,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
		{
			ID:            "default_gpt_3_5",
			Pattern:       "gpt-3.5",
			Replacement:   "llm-3.5",
			IsRegex:       false,
			CaseSensitive: true,
			IsActive:      true,
			Mode:          FilterModeBoth,
		},
	}
}
